apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: robotupdates.robotics.example.com
spec:
  group: robotics.example.com
  names:
    kind: RobotUpdate
    listKind: RobotUpdateList
    plural: robotupdates
    singular: robotupdate
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - robotName
                - targetRelease
              properties:
                robotName:
                  type: string
                  description: "The name of the Robot instance being updated."
                targetRelease:
                  type: string
                  description: "The name of the RobotRelease object to deploy."
                currentRelease:
                  type: string
                  description: "The name of the current RobotRelease object (optional; null for initial deployment)."
            status:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - InProgress
                    - Deployed
                    - Failed
                  description: "The status of the update process."
                lastUpdate:
                  type: string
                  format: date-time
                  description: "The timestamp of the last update attempt."
      subresources:
        status: {}